### ISSUE TITLE
script replace is not work when using single quote

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [samrum/vite-plugin-web-extension#111]
I have a project where the prettier plugin will replace all double quotes with single quotes

The following code is working
```
<script type='module' src="./main.ts"></script>
```

The following is the formatted code, and the script replacement will be invalid at this time
```
<script type='module' src='./main.ts'></script>
```

**Comment by samrum** [comment]
Just to confirm, is this only an issue with HMR/dev mode?

**Comment by samrum** [comment]
Right, yeah, should be simple to fix, thanks
