### ISSUE TITLE
CSS issue if importing some svelte in contentScript AND in options

### ISSUE THREAD

**Issue by HugoGresse** [samrum/vite-plugin-web-extension#12]
I wanted to have a common TabBar.svelte used in the contentScript app as well as in the options App. 

So the file architecture look like 

```
/entries/contentScript/primary/App.svelte (import ~/lib/TabBar.svelte)
/entries/options/App.svelte (import ~/lib/TabBar.svelte)
/lib/TabBar.svelte
```

The issue is as soon as the options App.svelte import the TabBar, the `contentScript/primary/main.z2EEd.css` is not longer generated upon build. 
For know I'm duplicating the file to prevent this issue, I've no clue how to fix this correctly though. 

My repo is here: https://github.com/HugoGresse/app-store-review-templates 
You'll need to import the `App.svelte` from the contentScript into `options/App.svelte`

**Comment by samrum** [comment]
Thanks for the repo that demonstrates the issue! I have a branch that refactors the way chunk assets are processed for Vite 2.9 [here](https://github.com/samrum/vite-plugin-web-extension/tree/vite-2.9.0) that may fix it. I can test it with your repo later.

**Comment by HugoGresse** [comment]
I can test it quickly as soon as you release a snapshot! The repo does not directly reproduce the issue, you'll need to remove the duplicate file from `lib/` and change the import in `options/App.svelte`

**Comment by samrum** [comment]
I checked and made some tweaks to that branch and it'll fix that issue. It'll be part of an upcoming 1.0.0 release, though there are some breaking changes that'll require some small code changes on your end.

**Comment by HugoGresse** [comment]
I can confirm the version 1.0.2 does fix the issue. Thanks!
