### ISSUE TITLE
Adjusting the example in creating a manifestV3 project?

### ISSUE THREAD

**Issue by chillcicada** [samrum/vite-plugin-web-extension#137]
In the latest [chrome manifest v3 format reference](https://developer.chrome.com/docs/extensions/reference/manifest#optional), the "authors" key only accepts an email object. When using `npm init @samrum/vite-plugin-web-extension` to create a manifestV3 project, should the given example be adjusted accordingly?

```txt
# Explanation of the "author" key in the latest chrome manifest v3 format reference
"author": Specifies the email address of the account that was used to create the extension.
```

```ts
// "@types/chrome": "^0.0.258",
// chrome.runtime.ManifestBase
author?: {
    email: string;
} | undefined;
```

**Comment by keyding** [comment]
See [PR](https://github.com/samrum/create-vite-plugin-web-extension/pull/44).
