### ISSUE TITLE
Update template to use Svelte 5 🙏

### ISSUE THREAD

**Issue by Extarys** [samrum/vite-plugin-web-extension#147]
Svelte 5 is officially out and backward compatible with Svelte 4.

I tried updating it myself in package.json, but runes throws errors. Updating the other libraries to the latest version also throws various errors when trying to run the extension.

**Comment by Aixata** [comment]
npx sv migrate svelte-5
npm i --force

There's a migration script, so far I only tried this with the svelte+ts template and the only thing I had to change was making sveltePreprocess in svelte.config.js a named export. No issues with runes atm.
