### ISSUE TITLE
HMR Solution Not Working in Manifest V3

### ISSUE THREAD

**Issue by blake-regalia** [samrum/vite-plugin-web-extension#20]
This HMR solution for local development does not work in Manifest V3:
```js
(async()=>{await import('http://localhost:3000/src/contentScript.ts')})();
```

For example, Chrome reports:
```
Refused to load the script 'http://localhost:3000/src/contentScript.ts' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by samrum** [comment]
It’s mentioned in the features bit of the readme, but HMR isn’t supported in Manifest V3. You’d need to use vite in watch mode instead. 

There’s an open issue here that would fix HMR in extension pages: https://bugs.chromium.org/p/chromium/issues/detail?id=1290188

Content scripts, if they don’t inherit that option when it’s fixed (which they probably won’t), will need an additional issue/feature request opened to allow localhost resources to be loaded in V3 as well.

**Comment by blake-regalia** [comment]
I see -- thanks for the extra info!
