### ISSUE TITLE
Importing from within isolated function

### ISSUE THREAD

**Issue by blake-regalia** [samrum/vite-plugin-web-extension#21]
Not exactly sure how to approach this issue. Service Worker needs to execute a script dynamically using [`chrome.scripting.executeScript`](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript) with the `func` parameter, providing a function that will be serialized, sent across frames, and reconstructed on the other side. This creates a problem for importing anything from within the content script.

_service-worker.ts_
```ts
import ContentScript from './content-script';

chrome.runtime.onMessage.addListener((msg, sender) => {
  chrome.scripting.executeScript({
    target: {tabId:sender.tab.id},
    func: ContentScript,
    args: [secret],
  });
});
```

_content-script.ts_
```ts
import { say } from 'cowsay';  // this will never work anyway since it binds outside the scope of the function

export default async function(secret) {
  const { say } = await import('cowsay');  // this does not seem to work either

  console.log(say({text:secret});
}
```

**Comment by samrum** [comment]
I think there are two potential options.

The first would be to pass `say` in as an `arg` to your content-script function (may not work depending on how `say` is serialized):
_service-worker.ts_
```ts
import ContentScript from './content-script';
import { say } from 'cowsay';

chrome.runtime.onMessage.addListener((msg, sender) => {
  chrome.scripting.executeScript({
    target: {tabId:sender.tab.id},
    func: ContentScript,
    args: [secret, say],
  });
});
```

_content-script.ts_
```ts
export default async function(secret, say) {
  console.log(say({text:secret});
}
```

The second would be to generate a static JS file that you'd inject using `files` instead of `func`:
_service-worker.ts_
```ts
chrome.runtime.onMessage.addListener((msg, sender) => {
  chrome.scripting.executeScript({
    target: {tabId:sender.tab.id},
    files: ['outputContentScript.js'], // defined and generated by vite
  });
});
```

_content-script.ts_ - transpiled to outputContentScript.js at build time
```ts
import { say } from 'cowsay';

export default async function(secret) {
  console.log(say({text:secret});
}
```

The issue there would be forwarding values from the service worker context to the injected script. Could use a message from the content script to retrieve that from the service worker, though.

**Comment by samrum** [comment]
Anyways, there's not really an issue with the plugin here that I can see, just intricacies of working with `chrome.scripting.executeScript`, so I'm going to close this.

**Comment by blake-regalia** [comment]
@samrum Thanks for the response -- the argument approach is indeed what I needed, very clever! I hadn't thought of that. Totally appreciate your willingness to help me out via GH issues albeit unorthodox ;)

**Comment by blake-regalia** [comment]
For anyone else who might find this same issue -- passing the function does not work in most cases. I am still trying to figure out a sane way to do this. I will likely resort to using a custom plugin.
