### ISSUE TITLE
Question - content script

### ISSUE THREAD

**Issue by heathsnee** [samrum/vite-plugin-web-extension#23]
Is there a way so that scripts injected via content script like this:

`runtime.getURL('src/lib.ts')`

```
const script = document.createElement('script')
script.type = 'module'
script.src = browser.runtime.getURL('src/lib.ts')

const head = document.head || document.getElementsByTagName('head')[0] || document.documentElement
head.appendChild(script)
```

are automatically added as well to web resources and paths resolved ?

also looks like if i include script in `web_accessible_resources` its not being handled, i cant find it in production build

```
	web_accessible_resources: [
		{
			matches: ['<all_urls>'],
			resources: ['src/lib.ts'],
		},
	],
```

**Comment by samrum** [comment]
With v2.0.0, this is possible via functionality added in #30. Defining the script as a web accessible resource should let you reference it via browser.runtime.getURL and a static path.

**Comment by Bighamster** [comment]
Many thanks!
Unfortunately, in 2.0.0 browser.runtime.getURL('src/lib.js') doesn't resolve path in 'assets/src/lib.{HASH}.js' 

Is there any way to solve this problem?

**Comment by Bighamster** [comment]
So far I've been using this hack

**src/lib.js**
```

export const pathname = (new URL(import.meta.url)).pathname;

```

**content-script.js**
```
import browser from "webextension-polyfill";
import { pathname } from "/src/lib.js";

function injectScript(file_path, tag) {
  var node = document.getElementsByTagName(tag)[0];
  var script = document.createElement("script");
  script.setAttribute("type", "module");
  script.setAttribute("src", file_path);
  node.appendChild(script);
}

injectScript(browser.runtime.getURL(pathname), "body");
```

**Comment by samrum** [comment]
Ah, right. They should really just be treated like content scripts and loaded via a loader file that uses the input filename so you're able to reference it statically. I'll re-open this issue to handle that.
