### ISSUE TITLE
How do you hot reload the extension?

### ISSUE THREAD

**Issue by lassebomh** [samrum/vite-plugin-web-extension#29]
I am aware of `pnpm run build` and `pnpm run serve:firefox` for running the build but is it possible to run the extension in a state where changes in the source will automatically be updated into the browser?

**Comment by rluiten** [comment]
What works for me is

- Run `npm run dev` then
- Run `npm run serve:chrome` or `npm run serve:firefox`

This is updating the extension for me right after a change is saved.
I logged an issue earlier which meant `dev` wasn't working so make sure you are using at least 
- @samrum/vite-plugin-web-extension 1.0.2

**Comment by lassebomh** [comment]
Thanks a lot. This was the solution I was looking for.

All the best
