### ISSUE TITLE
how to use browser.storage.sync in ContentScript

### ISSUE THREAD

**Issue by AnweshGangula** [samrum/vite-plugin-web-extension#44]
Hi I'm trying to set the user preferences and saved them in storage. I would like to use `storage.sync` instead of `storage.local`. 

But when I use `browser.storage.sync.get`, I get below error

> Cannot read properties of undefined (reading 'sync')

How to solve this?

**Comment by samrum** [comment]
Not related to the plugin, but you'd need to declare the `storage` permission in your manifest to have access to the storage API.
