### ISSUE TITLE
Clarify MV3-in-Firefox support in README

### ISSUE THREAD

**Issue by Vinnl** [samrum/vite-plugin-web-extension#61]
It wasn't entirely clear to me from the README whether MV3 in Firefox is supported. Trying it out it seems like no? Since the `serve:firefox` script did not pass `--firefox-preview mv3` to `web-ext`, the `manifest.ts` lists a `service_worker` (not yet supported by Firefox), and even after fixing those two issues, I get "Error: Extension is invalid".

To set expectations, it would be nice if the README had an indication of the current status of support for MV3 in Firefox :)

**Comment by samrum** [comment]
Good point! Firefox didn’t have any manifest V3 support at the time, but I do understand they have some experimental support now.
I haven’t looked into it much, but can definitely note that it’s not usable in the developer preview at the moment and see what’s required for it to work.

**Comment by samrum** [comment]
Added a "Firefox Experimental Manifest V3" example to the readme that explains how to configure the plugin to work with it. Requires v2.2.0 of the plugin.

**Comment by Vinnl** [comment]
Oh wow, experimental support is even better, nice!
