### ISSUE TITLE
Question: How to compile `content_scripts.css`?

### ISSUE THREAD

**Issue by lemonadee71** [samrum/vite-plugin-web-extension#74]
I have this in my config
```js
    content_scripts: [
      {
        matches: ['https://*.youtube.com/*'],
        js: ['src/inject.js'],
        css: ['src/inject.css'],
      },
    ],
```
And I have a tailwind css file
```css
/* inject.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I expect the `inject.css` to be compiled but it is only copy pasted into `dist/src`. Is this possible? I'm new to vite and web extensions.

**Comment by aleksolutions** [comment]
I would love to have this feature also, because when you are not using shadowDOM the styles loads much faster this way.

**Comment by samrum** [comment]
Opened a PR for an implementation of this that will forward content script css files as inputs to Vite. I tested it with some simple css, css with tailwind loaded in it like your example, and scss files and it seemed to work alright.
