### ISSUE TITLE
Rebuild doesn't always fire after saving a file

### ISSUE THREAD

**Issue by gorbit99** [samrum/vite-plugin-web-extension#78]
Hey!
For some reason, sometimes when I save a file that's part of the extension, it doesn't trigger a build in vite. The only workaround I've found is to then force save another file. 
I think this happens only for files set as "additionalInputs". For example right now I have a file that's eventually imported from a file that's in that list, and it refuses to build. But if I go one level up, it for some reason works fine.
Is this known, or is there a fix for this?

**Comment by samrum** [comment]
Are you using the `watch` or `dev` command? What do you mean by "additionalInputs"? Can you provide an example project?

**Comment by gorbit99** [comment]
Ignore, I accidentally found the wrong repository, it's just named the same.
