### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by blombard** [samrum/vite-plugin-web-extension#79]
Hello and thank you for your work.

Does this plugin support `Internationalization` and if yes, what should I do to enable it in my app?

Documenation:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
- https://developer.chrome.com/docs/extensions/reference/i18n/

**Comment by samrum** [comment]
Like regular Vite projects, a `public` directory will have its contents copied to the output directory, so you could place your `_locales` directory there.

Skimming through that first doc, and without testing, [Locale-dependent CSS](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#locale-dependent_css) is the only feature that may not work. Everything else should as described in that doc.
