### ISSUE TITLE
content scripts that have no imports are excluded from the build

### ISSUE THREAD

**Issue by DetachHead** [samrum/vite-plugin-web-extension#84]

**Comment by samrum** [comment]
Can you provide more information? Excluded how?
There's a test case for this that seems to indicate it's working ok: 
[contentWithNoImports.v3.test.ts ](https://github.com/samrum/vite-plugin-web-extension/blob/main/test/manifest/contentWithNoImports.v3.test.ts) and the [snapshot](https://github.com/samrum/vite-plugin-web-extension/blob/main/test/manifest/__snapshots__/contentWithNoImports.v3.test.ts.snap)

**Comment by DetachHead** [comment]
sorry i was in a rush when i raised this and didn't have time to make a minimal example.

i can't seem to reproduce this anymore so i'll close this. sorry to waste your time
