### ISSUE TITLE
Popup & Options pages inlude inline JS from HMR violating CSP

### ISSUE THREAD

**Issue by romanzipp** [samrum/vite-plugin-web-extension#85]
I ran into an issue where the extension popup & options page could not be loaded by Chromium (110.0.5481.77) or Google Chrome (110.0.5481.177) with the following error message:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' http://localhost:5173". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

![Screenshot 2023-03-07 at 19 53 53](https://user-images.githubusercontent.com/11266773/223522765-ec6297a1-6cfb-41ee-9535-f0837591df14.png)

The output popup `index.html` file contains some inline JS from `react-refresh` (HMR?)

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module">
import RefreshRuntime from "http://localhost:5173/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>

    <script type="module" src="http://localhost:5173/@vite/client"></script>

    <meta charset="UTF-8" />
    <title>Popup</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="http://localhost:5173/src/entries/options/main.jsx"></script>
  </body>
</html>
```

<details>
<summary><b>manifest.json</b></summary>

```json
{
  "author": "Roman Zipp",
  "description": "redacted",
  "name": "redacted",
  "version": "0.0.1",
  "content_scripts": [
    {
      "js": [
        "src/entries/contentScript/primary/main.js"
      ],
      "matches": [
        "redacted"
      ]
    },
    {
      "js": [
        "src/entries/contentScript/handshake/main.js"
      ],
      "matches": [
        "redacted"
      ]
    }
  ],
  "icons": {
    "16": "icons/16.png",
    "19": "icons/19.png",
    "32": "icons/32.png",
    "38": "icons/38.png",
    "48": "icons/48.png",
    "64": "icons/64.png",
    "96": "icons/96.png",
    "128": "icons/128.png",
    "256": "icons/256.png",
    "512": "icons/512.png"
  },
  "options_ui": {
    "page": "src/entries/options/index.html",
    "open_in_tab": true
  },
  "permissions": [
    "storage"
  ],
  "content_security_policy": {
    "extension_pages": "script-src 'self' http://localhost:5173; object-src 'self'"
  },
  "action": {
    "default_icon": {
      "16": "icons/16.png",
      "19": "icons/19.png",
      "32": "icons/32.png",
      "38": "icons/38.png"
    },
    "default_popup": "src/entries/popup/index.html"
  },
  "background": {
    "service_worker": "serviceWorker.js",
    "type": "module"
  },
  "host_permissions": [
    "redacted"
  ],
  "manifest_version": 3
}
```

</details>

According to the [CSP docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) there's no way to loosen the security policy in MV 2 & 3 for Chromium based browsers.

The `@samrum/vite-plugin-web-extension` package is up-to-date with version `3.1.1`

I've generated the extension code base via your [create-vite-plugin-web-extension](https://github.com/samrum/create-vite-plugin-web-extension) utility for React.

Let me know if you need any further information. Thanks for your great work so far!

**Comment by samrum** [comment]
Hmm, yeah, this is a Manifest V3 issue. In Manifest V2, this plugin automatically adds the hash for the inline script to the CSP and it works fine, but hashes are no longer supported in V3.

For the latest @vitejs/plugin-react, it seems like supporting that inline script in HTML isn't necessary anymore since HMR works alright without it.

Preventing viteDevServer!.transformIndexHtml from being called in devBuilder's writeManifestHtmlFile would be one way of fixing it. Probably via an option.

**Comment by maltoze** [comment]
still have this issue in version 5.0.0

![image](https://github.com/samrum/vite-plugin-web-extension/assets/18044730/71c76c00-2470-4000-bbe1-28e137c0eb98)

**Comment by romanzipp** [comment]
@maltoze A bit late, but requiring the `enableDevHmr` file in your Popup entry script resolves the isse.

**Comment by animber0** [comment]
> @maltoze A bit late, but requiring the `enableDevHmr` file in your Popup entry script resolves the issue.

Hi, I'm getting the same issue but for content scripts calling inline iframe code, how do I fix that if you would be so kind? I've tried importing the enableDevHmr, but that's not working either.

**Comment by chengfengfengwang** [comment]
> > @maltoze A bit late, but requiring the `enableDevHmr` file in your Popup entry script resolves the issue.
> 
> Hi, I'm getting the same issue but for content scripts calling inline iframe code, how do I fix that if you would be so kind? I've tried importing the enableDevHmr, but that's not working either.

the same to me

**Comment by alecmarcus** [comment]
> A bit late, but requiring the `enableDevHmr` file in your Popup entry script resolves the isse.
@romanzipp Sorry for the basic question but, from where?

**Comment by romanzipp** [comment]
@alecmarcus I added an import statement `import '~/enableDevHmr.js` in the same file that is setting up the react root (`createRoot(...).render(...)`). Maybe this helps - currently replying from mobile so I don't have any exact code snippets. Let me know if this works for you, otherwise i'll explain it in detail.

**Comment by pivanov** [comment]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/f5ecc860-4e9e-4286-8649-1efce389a2f8">

```typescript
import RefreshRuntime from '/@react-refresh';

if (import.meta.hot) {
  RefreshRuntime.injectIntoGlobalHook(window);
  window.$RefreshReg$ = () => {};
  window.$RefreshSig$ = () => (type) => type;
  window.__vite_plugin_react_preamble_installed__ = true;
}
```

```typescript
// popup/main.ts
import './enableDevHmr';
```

... and the error still exist when I open the popup.
I've try to add directly a import `enableDevHmr.js` to the html but this one still exist in my html:
```javascript
<script type="module">
  import RefreshRuntime from "/@react-refresh"
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
```
