### ISSUE TITLE
content script in dev mode is not working on firefox

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [samrum/vite-plugin-web-extension#87]
> WebExtension content scripts may only load modules with moz-extension URLs and not: “http://localhost:5173/src/entries/contentScript/primary/main.ts”.

![图片](https://user-images.githubusercontent.com/52521836/229097138-2a4c2be2-7917-4541-b479-9edd3001a69e.png)

**Comment by Firerrd** [comment]
work around: use `vite build --watch` instead `vite`

**Comment by samrum** [comment]
Yeah, until Firefox supports loading modules from localhost in a content script, you won't be able to use this plugins implementation of dev mode with it. Like the previous comment says, using watch with build is an alternative or developing in Chromium which supports it.
