### ISSUE TITLE
Feat Request: Set hash route in manifest entry file.

### ISSUE THREAD

**Issue by imrockpan** [samrum/vite-plugin-web-extension#90]
I really hope that hash route can be set in the manifest entry file.
It is very useful in the following usage scenarios:

```json5
{
  // ...
  "action": {
    "default_popup": "src/app.html#/popup/dashboard"
  },
  "options_page": "src/app.html#/options",
  // ...
}
```

Multiple pages are in App, it can reduce my template code.

**Comment by samrum** [comment]
It seems like Chrome supports hashes and even query parameters in manifest.json, so it should be possible.

Would need to update the input/output parsing of manifest HTML files so they're maintained on builds.

**Comment by imrockpan** [comment]
> It seems like Chrome supports hashes and even query parameters in manifest.json, so it should be possible.
> 
> Would need to update the input/output parsing of manifest HTML files so they're maintained on builds.

That's great, thanks for responding so quickly. 🙏
Super awesome plugin, saved me a lot of time. 🚀
